/*
-- Query: SELECT * FROM degree
LIMIT 0, 1000

-- Date: 2016-04-11 10:50
*/
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00001','Ph.D.(Computer Science)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00002','Ph.D.(Chemical Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00003','M.Tech.(ICT)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00003','Ph.D.(Computer Science)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00004','M. Sc. Physics');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00004','Ph D (Physics)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00005','M.Sc.(Chemistry)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00005','M.Tech.(Corrosion Science)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00005','Ph.D(Materials Science)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00006','B.Tech.(Chemical Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00006','M.Tech.(Chemical Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00006','Ph.D.(Chemical Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00007','B.E.(IC)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00008','B.Tech.(Chemical Engg)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00008','M.S.(Chem.Engg)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00008','Ph.D.(Tech.)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00009','Ph.D.(Physics)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00010','B.E.(Mechatronics Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00010','M.Sc.(Control Systems)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00010','MBA');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00010','MS');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00011','Ph.D.(Electronic Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00012','Ph.D.(mathematics)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00013','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00013','Ph.D.');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00014','B.E.(Telecommunications)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00014','M.Tech.(EE)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00015','B.E.(Electronics and Telecommunication Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00015','M.E.(Digital Systems)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00015','Ph.D.(Electronics and Telecommunication Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00016','M.Phil(English)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00016','Ph.D.(English)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00017','Ph.D.(Chemical Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00018','M.Sc(Chemistry)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00018','Ph.D.(Chemistry)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00019','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00020','M.Sc');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00020','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00021','M.Sc');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00021','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00021','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00022','Ph.D(Electrical & Computer Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('A00023','M.S.E.(Electrical Engineering)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00001','B.E.(Instrumentation & Control)');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00002','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00002','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00003','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00003','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00004','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00004','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00005','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00005','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00006','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00006','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00007','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00007','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00008','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00008','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00009','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00009','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00010','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00010','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00011','M.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('B00011','Ph.D');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00001','B.E');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00002','B.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00003','B.E');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00004','B.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00005','B.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00006','B.E');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00007','B.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00008','B.E');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00009','B.Tech');
INSERT INTO `degree` (`StaffID`,`Degree`) VALUES ('S00010','B.E');
